[package]
name = "console_app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "console_app"
path = "src/main.rs"

[dependencies]
game_core = { path = "../game_core"}
platform  = { path = "../platform" }
colog = "1.4.0"
colored = "3.0.0"
env_logger = "0.11.8"
log = "0.4.29"
